import Config

# Configure your database
config :ashy_walnut_desk, AshyWalnutDesk.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "ashy_walnut_desk_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :ashy_walnut_desk, AshyWalnutDeskWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  # Stable dev-only placeholder. `:prod` reads `SECRET_KEY_BASE` from
  # the environment via `config/runtime.exs` and raises if missing.
  # If you want a unique dev value, set `SECRET_KEY_BASE` in your
  # local environment — `mix phx.gen.secret` produces a 64-byte value.
  secret_key_base:
    System.get_env("SECRET_KEY_BASE") ||
      "DEV_PLACEHOLDER_secret_key_base_replace_via_env_or_runtime_exs_a",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:ashy_walnut_desk, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:ashy_walnut_desk, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :ashy_walnut_desk, AshyWalnutDeskWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/ashy_walnut_desk_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :ashy_walnut_desk, dev_routes: true

# Story 3.fix: explicit dev defaults for the two app secrets.
# Previously these were set at the top of `config/runtime.exs`
# (which runs in every env, including prod). Scoped here so a prod
# release missing the env vars fails fast in the runtime.exs prod
# block instead of silently using these dev-only constants.
config :ashy_walnut_desk,
  identifier_hash_salt: System.get_env("IDENTIFIER_HASH_SALT") || "dev-only-identifier-hash-salt",
  ash_authentication_secret: System.get_env("ASH_AUTHENTICATION_SECRET") || "dev-only-secret"

config :ashy_walnut_desk, AshyWalnutDesk.Mailer, adapter: Swoosh.Adapters.Local

# Local dev: allow sign-up so `mix phx.server` works without env wiring.
config :ashy_walnut_desk, :registration_enabled?, true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
