import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :ashy_walnut_desk, AshyWalnutDeskWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# F6: enable strict CSP in prod (LiveReloader / LiveDashboard are
# off in prod, so their inline-script CSP violations don't apply).
config :ashy_walnut_desk, :strict_csp?, true

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
