defmodule AshyWalnutDesk.AdminOnlyVersions do
  @moduledoc """
  Paper-trail Version mixin: admin-only reads on every `Version`
  resource generated by `AshPaperTrail.Resource`.

  Use from a resource's `paper_trail` block:

      paper_trail do
        version_extensions(authorizers: [Ash.Policy.Authorizer])
        mixin(AshyWalnutDesk.AdminOnlyVersions)
      end

  Every resource that opts into paper-trail uses the same policy, so
  one shared mixin keeps the rule in one place. Add a per-resource
  mixin only if its Version table needs different rules.
  """

  defmacro __using__(_opts) do
    quote do
      policies do
        policy action_type(:read) do
          authorize_if(actor_attribute_equals(:role, :admin))
        end
      end
    end
  end
end
