defmodule AshyWalnutDesk.Repo.Migrations.AddManuals do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:manuals_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:manuals, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:manuals_versions) do
      modify :version_source_id,
             references(:manuals,
               column: :id,
               name: "manuals_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:manuals) do
      add :title, :text, null: false
      add :slug, :text, null: false
      add :body, :text, null: false
      add :revision, :bigint, null: false, default: 1
      add :status, :text, null: false, default: "active"
      add :deleted_at, :utc_datetime_usec

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:manuals, [:slug], unique: true)

    create unique_index(:manuals, [:slug], name: "manuals_unique_slug_index")
  end

  def down do
    drop_if_exists unique_index(:manuals, [:slug], name: "manuals_unique_slug_index")

    drop_if_exists index(:manuals, [:slug])

    alter table(:manuals) do
      remove :updated_at
      remove :created_at
      remove :deleted_at
      remove :status
      remove :revision
      remove :body
      remove :slug
      remove :title
    end

    drop constraint(:manuals_versions, "manuals_versions_version_source_id_fkey")

    alter table(:manuals_versions) do
      modify :version_source_id, :uuid
    end

    drop table(:manuals)

    drop table(:manuals_versions)
  end
end
