defmodule AshyWalnutDesk.Repo.Migrations.AddDraftAiRetrieval do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:drafts) do
      add :ai_retrieval, :map
    end
  end

  def down do
    alter table(:drafts) do
      remove :ai_retrieval
    end
  end
end
