defmodule AshyWalnutDesk.Repo.Migrations.AddDraftPersona do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:drafts) do
      add :persona_id,
          references(:personas,
            column: :id,
            name: "drafts_persona_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end
  end

  def down do
    drop constraint(:drafts, "drafts_persona_id_fkey")

    alter table(:drafts) do
      remove :persona_id
    end
  end
end
