defmodule AshyWalnutDesk.Repo.Migrations.PerfHotPathIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:inboxes, [:status, :created_at])

    create index(:conversations, [:identity_id, :channel_id])
  end

  def down do
    drop_if_exists index(:conversations, [:identity_id, :channel_id])

    drop_if_exists index(:inboxes, [:status, :created_at])
  end
end
