defmodule AshyWalnutDesk.Repo.Migrations.AddManualChunks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:manual_chunks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :revision, :bigint, null: false
      add :position, :bigint, null: false
      add :content, :text, null: false
      add :content_hash, :text, null: false
      add :embedding, :vector, size: 1024
      add :embedder, :text
      add :embedded_at, :utc_datetime_usec

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :manual_id,
          references(:manuals,
            column: :id,
            name: "manual_chunks_manual_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:manual_chunks, [:manual_id, :revision, :position], unique: true)
  end

  def down do
    drop constraint(:manual_chunks, "manual_chunks_manual_id_fkey")

    drop_if_exists index(:manual_chunks, [:manual_id, :revision, :position])

    drop table(:manual_chunks)
  end
end
