defmodule AshyWalnutDesk.Repo.Migrations.AddPersonaFoundation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:personas_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:personas, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:personas_versions) do
      modify :version_source_id,
             references(:personas,
               column: :id,
               name: "personas_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:personas) do
      add :name, :text, null: false
      add :slug, :text, null: false
      add :system_prompt, :text, null: false
      add :disclosure_text, :text, null: false
      add :guardrail_notes, :text
      add :model_override, :text
      add :status, :text, null: false, default: "active"
      add :deleted_at, :utc_datetime_usec

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:personas, [:slug], unique: true)

    create unique_index(:personas, [:slug], name: "personas_unique_slug_index")
  end

  def down do
    drop_if_exists unique_index(:personas, [:slug], name: "personas_unique_slug_index")

    drop_if_exists index(:personas, [:slug])

    alter table(:personas) do
      remove :updated_at
      remove :created_at
      remove :deleted_at
      remove :status
      remove :model_override
      remove :guardrail_notes
      remove :disclosure_text
      remove :system_prompt
      remove :slug
      remove :name
    end

    drop constraint(:personas_versions, "personas_versions_version_source_id_fkey")

    alter table(:personas_versions) do
      modify :version_source_id, :uuid
    end

    drop table(:personas)

    drop table(:personas_versions)
  end
end
