defmodule AshyWalnutDesk.Repo.Migrations.Story36CompensationTrigger do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:compensations) do
      add :trigger_initiated_at, :utc_datetime_usec
      add :adapter_response, :map
      add :error, :text
      add :outbound_idempotency_key, :text
    end
  end

  def down do
    alter table(:compensations) do
      remove :outbound_idempotency_key
      remove :error
      remove :adapter_response
      remove :trigger_initiated_at
    end
  end
end
