defmodule AshyWalnutDesk.Repo.Migrations.AddUsersOneAdminIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:users, [:role],
             name: "users_one_admin_idx",
             unique: true,
             where: "role = 'admin'"
           )
  end

  def down do
    drop_if_exists index(:users, [:role], name: "users_one_admin_idx")
  end
end
