defmodule AshyWalnutDesk.Repo.Migrations.AddAppointments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:appointments_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:appointments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:appointments_versions) do
      modify :version_source_id,
             references(:appointments,
               column: :id,
               name: "appointments_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:appointments) do
      add :scheduled_for, :utc_datetime_usec, null: false
      add :appointment_type, :text, null: false, default: "initial"
      add :status, :text, null: false, default: "scheduled"
      add :summary, :text, null: false
      add :deleted_at, :utc_datetime_usec

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :identity_id,
          references(:identities,
            column: :id,
            name: "appointments_identity_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :originating_event_id,
          references(:events,
            column: :id,
            name: "appointments_originating_event_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )

      add :recorded_by_id,
          references(:users,
            column: :id,
            name: "appointments_recorded_by_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:appointments, [:identity_id, :deleted_at])
  end

  def down do
    drop constraint(:appointments, "appointments_identity_id_fkey")

    drop constraint(:appointments, "appointments_originating_event_id_fkey")

    drop constraint(:appointments, "appointments_recorded_by_id_fkey")

    drop_if_exists index(:appointments, [:identity_id, :deleted_at])

    alter table(:appointments) do
      remove :recorded_by_id
      remove :originating_event_id
      remove :identity_id
      remove :updated_at
      remove :created_at
      remove :deleted_at
      remove :summary
      remove :status
      remove :appointment_type
      remove :scheduled_for
    end

    drop constraint(:appointments_versions, "appointments_versions_version_source_id_fkey")

    alter table(:appointments_versions) do
      modify :version_source_id, :uuid
    end

    drop table(:appointments)

    drop table(:appointments_versions)
  end
end
