defmodule AshyWalnutDesk.Repo.Migrations.Story34IdempotencyDedupe do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:inbound_deliveries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :provider, :text, null: false
      add :provider_message_id, :text, null: false
      add :received_at, :utc_datetime_usec, null: false
      add :outcome, :text, null: false
      add :intake_failure_reason, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:inbound_deliveries, [:received_at])

    create index(:inbound_deliveries, [:provider, :provider_message_id], unique: true)

    alter table(:actions) do
      add :outbound_idempotency_key, :text
    end
  end

  def down do
    alter table(:actions) do
      remove :outbound_idempotency_key
    end

    drop_if_exists index(:inbound_deliveries, [:provider, :provider_message_id])

    drop_if_exists index(:inbound_deliveries, [:received_at])

    drop table(:inbound_deliveries)
  end
end
