defmodule AshyWalnutDesk.Repo.Migrations.PerfAuditEventChainTopicIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:audit_events, [:chain_topic, :inserted_at])
  end

  def down do
    drop_if_exists index(:audit_events, [:chain_topic, :inserted_at])
  end
end
