defmodule AshyWalnutDesk.Repo.Migrations.AddEvents do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:events_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:events_versions) do
      modify :version_source_id,
             references(:events,
               column: :id,
               name: "events_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:events) do
      add :occurred_at, :utc_datetime_usec, null: false
      add :summary, :text, null: false
      add :body, :text
      add :deleted_at, :utc_datetime_usec

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :identity_id,
          references(:identities,
            column: :id,
            name: "events_identity_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :recorded_by_id,
          references(:users,
            column: :id,
            name: "events_recorded_by_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:events, [:identity_id, :deleted_at])
  end

  def down do
    drop constraint(:events, "events_identity_id_fkey")

    drop constraint(:events, "events_recorded_by_id_fkey")

    drop_if_exists index(:events, [:identity_id, :deleted_at])

    alter table(:events) do
      remove :recorded_by_id
      remove :identity_id
      remove :updated_at
      remove :created_at
      remove :deleted_at
      remove :body
      remove :summary
      remove :occurred_at
    end

    drop constraint(:events_versions, "events_versions_version_source_id_fkey")

    alter table(:events_versions) do
      modify :version_source_id, :uuid
    end

    drop table(:events)

    drop table(:events_versions)
  end
end
