defmodule AshyWalnutDesk.Repo.Migrations.Story33IdentityProvisional do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:identities) do
      add :provisional?, :boolean, null: false, default: false
      add :discovered_via, :text
    end
  end

  def down do
    alter table(:identities) do
      remove :discovered_via
      remove :provisional?
    end
  end
end
