defmodule AshyWalnutDesk.Repo.Migrations.Story3FixIdentityPrimaryIdentifier do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:identities) do
      add :primary_identifier, :text
    end
  end

  def down do
    alter table(:identities) do
      remove :primary_identifier
    end
  end
end
