defmodule AshyWalnutDesk.Repo.Migrations.Story35OutboundIdempotencyKey do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:messages) do
      add :outbound_idempotency_key, :text
    end
  end

  def down do
    alter table(:messages) do
      remove :outbound_idempotency_key
    end
  end
end
