defmodule AshyWalnutDesk.Repo.Migrations.Story22InteractionSkeletons do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:messages_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:messages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:messages_versions) do
      modify :version_source_id,
             references(:messages,
               column: :id,
               name: "messages_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:messages) do
      add :direction, :text, null: false
      add :body, :text, null: false
      add :sent_at, :utc_datetime_usec
      add :deleted_at, :utc_datetime_usec

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :conversation_id, :uuid, null: false
      add :approved_by_id, :uuid
    end

    create table(:inboxes_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:inboxes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:inboxes_versions) do
      modify :version_source_id,
             references(:inboxes,
               column: :id,
               name: "inboxes_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:inboxes) do
      add :status, :text, null: false
      add :summary, :text, null: false
      add :deleted_at, :utc_datetime_usec

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :conversation_id, :uuid, null: false
      add :recorded_by_id, :uuid, null: false
    end

    create table(:drafts_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:drafts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:drafts_versions) do
      modify :version_source_id,
             references(:drafts,
               column: :id,
               name: "drafts_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:drafts) do
      add :body, :text, null: false
      add :compensation_body, :text
      add :status, :text, null: false
      add :approved_at, :utc_datetime_usec
      add :ai_prompt, :text
      add :ai_model, :text
      add :ai_response, :text
      add :ai_validator_output, :map
      add :deleted_at, :utc_datetime_usec

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :inbox_id,
          references(:inboxes,
            column: :id,
            name: "drafts_inbox_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :approved_by_id,
          references(:users,
            column: :id,
            name: "drafts_approved_by_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    create table(:conversations_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:conversations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:messages) do
      modify :conversation_id,
             references(:conversations,
               column: :id,
               name: "messages_conversation_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )

      modify :approved_by_id,
             references(:users,
               column: :id,
               name: "messages_approved_by_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    alter table(:inboxes) do
      modify :conversation_id,
             references(:conversations,
               column: :id,
               name: "inboxes_conversation_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )

      modify :recorded_by_id,
             references(:users,
               column: :id,
               name: "inboxes_recorded_by_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    alter table(:conversations_versions) do
      modify :version_source_id,
             references(:conversations,
               column: :id,
               name: "conversations_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:conversations) do
      add :subject, :text, null: false
      add :deleted_at, :utc_datetime_usec

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :identity_id,
          references(:identities,
            column: :id,
            name: "conversations_identity_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :channel_id, :uuid, null: false
    end

    create table(:compensations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false
      add :body, :text, null: false
      add :triggered_at, :utc_datetime_usec

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :action_id, :uuid, null: false
    end

    create index(:compensations, [:action_id], unique: true)

    create table(:channels_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:channels, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:conversations) do
      modify :channel_id,
             references(:channels,
               column: :id,
               name: "conversations_channel_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    alter table(:channels_versions) do
      modify :version_source_id,
             references(:channels,
               column: :id,
               name: "channels_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:channels) do
      add :slug, :text, null: false
      add :display_name, :text, null: false
      add :adapter_module, :text, null: false
      add :enabled?, :boolean, null: false, default: true
      add :deleted_at, :utc_datetime_usec

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:channels, [:slug], unique: true)

    create table(:audit_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :chain_topic, :text, null: false
      add :event_type, :text, null: false
      add :subject_kind, :text, null: false
      add :subject_id, :uuid, null: false
      add :payload, :map, null: false
      add :prev_hash, :text
      add :hash, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :actor_id,
          references(:users,
            column: :id,
            name: "audit_events_actor_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    create table(:actions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:compensations) do
      modify :action_id,
             references(:actions,
               column: :id,
               name: "compensations_action_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    alter table(:actions) do
      add :status, :text, null: false
      add :adapter_response, :map
      add :executed_at, :utc_datetime_usec
      add :error, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :draft_id,
          references(:drafts,
            column: :id,
            name: "actions_draft_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      add :channel_id,
          references(:channels,
            column: :id,
            name: "actions_channel_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create index(:actions, [:draft_id], unique: true)
  end

  def down do
    drop constraint(:actions, "actions_draft_id_fkey")

    drop constraint(:actions, "actions_channel_id_fkey")

    drop_if_exists index(:actions, [:draft_id])

    alter table(:actions) do
      remove :channel_id
      remove :draft_id
      remove :updated_at
      remove :created_at
      remove :error
      remove :executed_at
      remove :adapter_response
      remove :status
    end

    drop constraint(:compensations, "compensations_action_id_fkey")

    alter table(:compensations) do
      modify :action_id, :uuid
    end

    drop table(:actions)

    drop constraint(:audit_events, "audit_events_actor_id_fkey")

    drop table(:audit_events)

    drop_if_exists index(:channels, [:slug])

    alter table(:channels) do
      remove :updated_at
      remove :created_at
      remove :deleted_at
      remove :enabled?
      remove :adapter_module
      remove :display_name
      remove :slug
    end

    drop constraint(:channels_versions, "channels_versions_version_source_id_fkey")

    alter table(:channels_versions) do
      modify :version_source_id, :uuid
    end

    drop constraint(:conversations, "conversations_channel_id_fkey")

    alter table(:conversations) do
      modify :channel_id, :uuid
    end

    drop table(:channels)

    drop table(:channels_versions)

    drop_if_exists index(:compensations, [:action_id])

    drop table(:compensations)

    drop constraint(:conversations, "conversations_identity_id_fkey")

    alter table(:conversations) do
      remove :channel_id
      remove :identity_id
      remove :updated_at
      remove :created_at
      remove :deleted_at
      remove :subject
    end

    drop constraint(:conversations_versions, "conversations_versions_version_source_id_fkey")

    alter table(:conversations_versions) do
      modify :version_source_id, :uuid
    end

    drop constraint(:inboxes, "inboxes_conversation_id_fkey")

    drop constraint(:inboxes, "inboxes_recorded_by_id_fkey")

    alter table(:inboxes) do
      modify :recorded_by_id, :uuid
      modify :conversation_id, :uuid
    end

    drop constraint(:messages, "messages_conversation_id_fkey")

    drop constraint(:messages, "messages_approved_by_id_fkey")

    alter table(:messages) do
      modify :approved_by_id, :uuid
      modify :conversation_id, :uuid
    end

    drop table(:conversations)

    drop table(:conversations_versions)

    drop constraint(:drafts, "drafts_inbox_id_fkey")

    drop constraint(:drafts, "drafts_approved_by_id_fkey")

    alter table(:drafts) do
      remove :approved_by_id
      remove :inbox_id
      remove :updated_at
      remove :created_at
      remove :deleted_at
      remove :ai_validator_output
      remove :ai_response
      remove :ai_model
      remove :ai_prompt
      remove :approved_at
      remove :status
      remove :compensation_body
      remove :body
    end

    drop constraint(:drafts_versions, "drafts_versions_version_source_id_fkey")

    alter table(:drafts_versions) do
      modify :version_source_id, :uuid
    end

    drop table(:drafts)

    drop table(:drafts_versions)

    alter table(:inboxes) do
      remove :recorded_by_id
      remove :conversation_id
      remove :updated_at
      remove :created_at
      remove :deleted_at
      remove :summary
      remove :status
    end

    drop constraint(:inboxes_versions, "inboxes_versions_version_source_id_fkey")

    alter table(:inboxes_versions) do
      modify :version_source_id, :uuid
    end

    drop table(:inboxes)

    drop table(:inboxes_versions)

    alter table(:messages) do
      remove :approved_by_id
      remove :conversation_id
      remove :updated_at
      remove :created_at
      remove :deleted_at
      remove :sent_at
      remove :body
      remove :direction
    end

    drop constraint(:messages_versions, "messages_versions_version_source_id_fkey")

    alter table(:messages_versions) do
      modify :version_source_id, :uuid
    end

    drop table(:messages)

    drop table(:messages_versions)
  end
end
