defmodule AshyWalnutDesk.Repo.Migrations.FixPendingCodegen do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:identities, [:primary_identifier_hash], unique: true)
  end

  def down do
    drop_if_exists index(:identities, [:primary_identifier_hash])
  end
end
