defmodule AshyWalnutDesk.Repo.Migrations.CreateIdentities do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:identities_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false
      add :version_action_name, :text, null: false
      add :version_source_id, :uuid, null: false
      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:identities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:identities_versions) do
      modify :version_source_id,
             references(:identities,
               column: :id,
               name: "identities_versions_version_source_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:identities) do
      add :display_name, :citext, null: false
      add :primary_identifier_hash, :text, null: false
      add :notes_summary, :text
      add :deleted_at, :utc_datetime_usec

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_by_id,
          references(:users,
            column: :id,
            name: "identities_created_by_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:identities, "identities_created_by_id_fkey")

    alter table(:identities) do
      remove :created_by_id
      remove :updated_at
      remove :created_at
      remove :deleted_at
      remove :notes_summary
      remove :primary_identifier_hash
      remove :display_name
    end

    drop constraint(:identities_versions, "identities_versions_version_source_id_fkey")

    alter table(:identities_versions) do
      modify :version_source_id, :uuid
    end

    drop table(:identities)

    drop table(:identities_versions)
  end
end
